name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release

jobs:
   build:
    # TODO: xethub-poc: undo when poc complete
    if: false
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: huggingface_hub
      languages: cn de fr en hi ko
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
