name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release

jobs:
   build:
    uses: lysandrejik/doc-builder/.github/workflows/build_main_documentation.yml@lysandrejik-workflow
    with:
      commit_sha: ${{ github.sha }}
      package: huggingface_hub
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}