name: Inference API Python-tests
on:
  push:
    paths:
      - "api-inference-community/**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - run: |
          sudo apt-get install ffmpeg

      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: api-inference-community
        run: |
          pip install --upgrade pip
          pip install pytest pillow httpx huggingface_hub
          pip install -e .
      - run: make test
        working-directory: api-inference-community
