name: Python quality

on:
  push:
    branches:
      - main
    paths-ignore:
      - "js/**"
      - "api-inference-community/**"
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths-ignore:
      - "js/**"
      - "api-inference-community/**"

jobs:
  check_code_quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Setup venv
      - name: Setup venv + uv
        run: |
          pip install --upgrade uv
          uv venv
          source .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV  # See https://stackoverflow.com/a/74669486

      - name: Install dependencies
        run: uv pip install "huggingface_hub[dev] @ ."
      - run: ruff check tests src contrib # linter
      - run: ruff format --check tests src contrib # formatter
      - run: python utils/check_contrib_list.py
      - run: python utils/check_static_imports.py
      - run: python utils/generate_async_inference_client.py
      - run: python utils/generate_inference_types.py

      # Run type checking at least on huggingface_hub root file to check all modules
      # that can be lazy-loaded actually exist.
      - run: mypy src/huggingface_hub/__init__.py --follow-imports=silent --show-traceback

      # Run mypy on full package
      - run: mypy src
